# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/dotNET-Core.gitlab-ci.yml

variables:
  NUGET_PACKAGES_DIRECTORY: ".nuget"

default:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm --version
    - dotnet tool restore
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
  tags:
    - shared-fi

stages:
  - build
  - format

build:
  stage: build
  script:
    - dotnet build --no-restore

format:csharpier:
  stage: format
  script:
    - dotnet csharpier --check .
